#role
sudo: required 

#os
dist: trusty


#bahasa
language: php

#versi
php:
  - 7.1

#ngbranch
branches:
  only:
    - master
    - develop

#sebelum instal
before_instal:
  - wget https://phar.phpunit.de/phpunit-6.5.phar
  - chmod +x phpunit-6.5.phar
  - sudo mv phpunit-6.5.phar /usr/local/bin/phpunit
  - phpunit --version
#instal
instal:
#sebelum script
before_script:
#script
script:
